### ISSUE TITLE
Investigator Release v0.5.0 BLOCKER

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#168]
This release of investigator is migrating more components of Thoth to a Kafka based messaging. In addition to that, we reschedule adviser workflows that have not created results before. The rescheduled workflow should create more meaningful advise as Thoth learned about packages being used (and where unknown on the first run) and help Thoth keeping its knowledge up to date.

Migration:
- [x] Use new thoth-messaging https://github.com/thoth-station/messaging/issues/230

Tasks:
- [x] adviser re run from investigator https://github.com/thoth-station/investigator/issues/63
- [x] graph-refresh job runs as Kafka (https://github.com/thoth-station/thoth-application/issues/423)
- [x] Investigator can consume graph-refresh producer messages (https://github.com/thoth-station/investigator/issues/204)
- [x] package-release-job runs as Kafka producer (https://github.com/thoth-station/thoth-application/issues/422)
- [x] Investigator can consume package-release producer messages (https://github.com/thoth-station/investigator/issues/203)
- [x] User-API runs as Kafka producer (https://github.com/thoth-station/thoth-application/issues/427)
- [x] Investigator can consume User-API messages (https://github.com/thoth-station/investigator/issues/205)

- [x] Have limit in messages consumed based on resource: https://github.com/thoth-station/investigator/issues/155

Blocked By:
- [x] https://github.com/thoth-station/investigator/issues/197

**Comment by goern** [comment]
Can we get a document on the reconciliation logic of investigator? How it acts in certain situations, what humans need to do?
